package pack2;

public class TryCatchFinally4 {

	public static void main(String[] args) {
		
		try {
			// Critical statements which may raise an exception
		}
		catch(ArithmeticException e) {
			// Solution for the Arithmetic exception which raises in the try-block
		}
		catch(NullPointerException e1) {
			// Solution for the NullPointerException which raises in the try-block
		}
		catch(ArrayIndexOutOfBoundsException e2) {
			// Solution for the ArrayIndexOutOfBoundsException which raises in the try-block
		}
	}

}
